services:
  postgres:
    image: postgres:18.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: P@ssw0rd123!
      POSTGRES_DB: taskflow_db
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d taskflow_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-network

  api-server:
    image: ${DOCKER_REGISTRY-}api-server
    container_name: api-server
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MyDbContext=Host=postgres;Port=5432;Database=taskflow_db;Username=db_user;Password=P@ssw0rd123!
    ports:
      - "5000:80"
    networks:
      - monitoring-network
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - monitoring-network
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    networks:
      - monitoring-network

volumes:
  postgres-data:

networks:
  monitoring-network:
    driver: bridge
