version: '3.8'

services:
  postgres:
    image: postgres:18.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: P@ssw0rd123!
      POSTGRES_DB: taskflow_db
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d taskflow_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - monitoring-network

  taskflow-dotnet-server:
    image: ${DOCKER_REGISTRY-}taskflow-dotnet-server
    container_name: taskflow_app_container
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:80"
      - "5001:81"
    networks:
      - monitoring-network
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring-network
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring-network

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring-network:
    driver: bridge
