version: '3.9'

services:
  postgres:
    image: postgres:18.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: P@ssw0rd123!
      POSTGRES_DB: taskflow_db
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d taskflow_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  taskflow-dotnet-server:
    image: ${DOCKER_REGISTRY-}taskflow-dotnet-server
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
